let passwords = [
    {
        id:1,
        username:"nurillo",
        firstName:"Nurillo",
        lastName:"Suyunboyev",
        password:"123"
    },
    {
        id:2,
        username:"ulug'bek",
        firstName:"Ulug'bek",
        lastName:"Raxmatullayev",
        password:"123"
    },
    {
        id:3,
        username:"shamsiddin",
        firstName:"Shamsiddin",
        lastName:"Boyqulov",
        password:"123"
    },
    {
        id:4,
        username:"sarvar",
        firstName:"Sarvar",
        lastName:"A'zamov",
        password:"123"
    },
    {
        id:5,
        username:"nigora",
        firstName:"Nigora",
        lastName:"Xasanova",
        password:"123"
    },
    {
        id:6,
        username:"laylo",
        firstName:"Laylo",
        lastName:"Ismatullayeva",
        password:"123"
    },
    {
        id:7,
        username:"muslima",
        firstName:"Muslima",
        lastName:"Yoqubova",
        password:"123"
    },
    {
        id:8,
        username:"dilnoza",
        firstName:"Dilnoza",
        lastName:"Raxmatullaeva",
        password:"123"
    },
    {
        id:9,
        username:"roziya",
        firstName:"Roziya",
        lastName:"Gayratillayeva",
        password:"123"
    },
    {
        id:10,
        username:"hamroz",
        firstName:"Hamroz",
        lastName:"Nuriddinov",
        password:"123"
    },
    {
        id:11,
        username:"ibrohim",
        firstName:"Ibrohim",
        lastName:"Shukurullayev",
        password:"123"
    },
    {
        id:12,
        username:"abduvohob",
        firstName:"Abduvahob",
        lastName:"Mirzaahmedov",
        password:"123"
    },
    {
        id:13,
        username:"abdulloh",
        firstName:"Abdulloh",
        lastName:"Sultonmurodov",
        password:"123"
    },
    {
        id:14,
        username:"muhammadali",
        firstName:"Muhammadali",
        lastName:"Rustambekov",
        password:"123"
    }
]